spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpatest?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: java
    password: javapwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

